# Generated by Django 6.0.6 on 2026-07-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_python', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
